library(dplyr)

# Read in quality assessment columns
df_QA <- read.csv("data/covidence_export_data_12152025.csv") %>%
  dplyr::select(Title,
         First.Author,
         Year,
         Journal,
         Sample.Characteristics,
         Accelerometry.Settings,
         Protocol.Design,
         Criterion,
         Was.the.validation.method.of.the.study.adequate.,
         Sample.Characteristics.supporting.text,
         Accelerometry.Settings.supporting.text,
         Protocol.Design.supporting.text,
         Criterion.supporting.text,
         Was.the.validation.method.of.the.study.adequate..supporting.text
  )

# Read in rest of data
df_data <- read.csv("data/covidence_export_data_12152025.csv") %>%
  dplyr::select(Title,
         First.Author,
         Year,
         Journal,
         Physical.Activity.Outcomes.Evaluated,
         If.outcome.was.categorical..list.categories.here.,
         Population.Age.Range,
         Did.the.research.team.collect.their.own.data.,
         If.the.research.team.used.an.existing.dataset..what.was.the.dataset.,
         Protocol.Setting,
         Protocol.Activities...Categories,
         Protocol.Activities...Type.of.movement,
         If.protocol.was.structured.and.activities.listed..please.list.them.below.separated.by.commas.,
         Accelerometer.based.Device,
         Sensors.used,
         Wear.Locations.Included,
         Criterion.Measure,
         Algorithm.s..Included.in.Analysis,
         What.model.evaluation.technique.was.used.,
         What.were.the.primary.metrics.used.to.compare.performance.between.wear.locations.,
         Total.number.of.participants,
         Total.number.of.female.participants,
         Total.number.of.male.participants,
         Age.Mean,
         Age.SD,
         BMI.Mean,
         BMI.SD,
         Corresponding.Metrics.and.Sites.for.the.following.table,
         Site.1.Metric.1,
         Site.1.Metric.2,
         Site.1.Metric.3,
         Site.1.Metric.4,
         Site.1.Metric.5,
         Site.1.Metric.6,
         Site.2.Metric.1,
         Site.2.Metric.2,
         Site.2.Metric.3,
         Site.2.Metric.4,
         Site.2.Metric.5,
         Site.2.Metric.6,
         Site.3.Metric.1,
         Site.3.Metric.2,
         Site.3.Metric.3,
         Site.3.Metric.4,
         Site.3.Metric.5,
         Site.3.Metric.6,
         Site.4.Metric.1,
         Site.4.Metric.2,
         Site.4.Metric.3,
         Site.4.Metric.4,
         Site.4.Metric.5,
         Site.4.Metric.6,
         Site.5.Metric.1,
         Site.5.Metric.2,
         Site.5.Metric.3,
         Site.5.Metric.4,
         Site.5.Metric.5,
         Site.5.Metric.6,
         Site.6.Metric.1,
         Site.6.Metric.2,
         Site.6.Metric.3,
         Site.6.Metric.4,
         Site.6.Metric.5,
         Site.6.Metric.6,
         Site.7.Metric.1,
         Site.7.Metric.2,
         Site.7.Metric.3,
         Site.7.Metric.4,
         Site.7.Metric.5,
         Site.7.Metric.6,
         Site.8.Metric.1,
         Site.8.Metric.2,
         Site.8.Metric.3,
         Site.8.Metric.4,
         Site.8.Metric.5,
         Site.8.Metric.6,
         Additional.Notes
  )


# Save data
saveRDS(df_QA, file = "data/quality_assessment_data.RDA")
saveRDS(df_data, file = "data/extraction_data.RDA")
